// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.AlreadyOnLatestVerInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.AutoupdateToggle")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ChangedWatcher")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CheckForUpdates")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CheckForUpdatesStartToggle")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CheckForUpdatesStartToggleInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CheckingForUpdatesInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CopyImageToClipboard")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CreatedWatcher")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.CutFileToClipboard")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DarkMode")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DarkModeInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DarkModeOnTooltip")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DeleteImageShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DeletedWatcher")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownloadFinsihedInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownloadingInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownloadLatest")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownloadLatestTooltip")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownsizeImage")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownsizeImageShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.DownsizeOnTooltip")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.EnableThumbnailList")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.EnableThumbnailListInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.FileNotFoundMsg")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ExploreImageLocationShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.FileType")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.FileTypeInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.NewVerAvailableInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.NextImageShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.NoInternetInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.OpenFileLocation")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.PauseAnimationShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.RemoveShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.RenamedWatcher")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ResetSettingsButton")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ShowThumbnailList")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.StretchImage")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.StretchImageInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.StretchImageShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.StretchOnTooltip")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ThemeAccent")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ThemeAccentInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ThumbnailListOnTooltip")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ThumbnailRes")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ThumbnailSize")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ShownLanguageInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.PreviousImageShortcut")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.AutoupdateToggleInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.ZoomSensitivity")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.UpdatingInfo")]
[assembly: SuppressMessage("Gu.Localization.Analyzers.Correctness", "GULOC07:Key does not match.", Justification = "<Pending>", Scope = "member", Target = "~P:FIVStandard.Properties.Resources.AllWatcher")]
