//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIVStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FIVStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Changes.
        /// </summary>
        public static string AllWatcher {
            get {
                return ResourceManager.GetString("AllWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version already installed.
        /// </summary>
        public static string AlreadyOnLatestVerInfo {
            get {
                return ResourceManager.GetString("AlreadyOnLatestVerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate file type with the program.
        /// </summary>
        public static string AssociateTypeTooltip {
            get {
                return ResourceManager.GetString("AssociateTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoupdate.
        /// </summary>
        public static string AutoupdateToggle {
            get {
                return ResourceManager.GetString("AutoupdateToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download and install new update..
        /// </summary>
        public static string AutoupdateToggleInfo {
            get {
                return ResourceManager.GetString("AutoupdateToggleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string ChangedWatcher {
            get {
                return ResourceManager.GetString("ChangedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if there are new updates when the program first starts up..
        /// </summary>
        public static string CheckForUpdatesStartToggleInfo {
            get {
                return ResourceManager.GetString("CheckForUpdatesStartToggleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdatesInfo {
            get {
                return ResourceManager.GetString("CheckingForUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to Clipboard.
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string CopyImageToClipboard {
            get {
                return ResourceManager.GetString("CopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedWatcher {
            get {
                return ResourceManager.GetString("CreatedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut File to Clipboard.
        /// </summary>
        public static string CutFileToClipboard {
            get {
                return ResourceManager.GetString("CutFileToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut to Clipboard.
        /// </summary>
        public static string CutToClipboard {
            get {
                return ResourceManager.GetString("CutToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Light and Dark theme..
        /// </summary>
        public static string DarkModeInfo {
            get {
                return ResourceManager.GetString("DarkModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode On.
        /// </summary>
        public static string DarkModeOnTooltip {
            get {
                return ResourceManager.GetString("DarkModeOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DeletedWatcher {
            get {
                return ResourceManager.GetString("DeletedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string DeleteImageShortcut {
            get {
                return ResourceManager.GetString("DeleteImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Finished.
        /// </summary>
        public static string DownloadFinsihedInfo {
            get {
                return ResourceManager.GetString("DownloadFinsihedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloadingInfo {
            get {
                return ResourceManager.GetString("DownloadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Latest.
        /// </summary>
        public static string DownloadLatest {
            get {
                return ResourceManager.GetString("DownloadLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the latest setup for the program.
        /// </summary>
        public static string DownloadLatestTooltip {
            get {
                return ResourceManager.GetString("DownloadLatestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsize Image.
        /// </summary>
        public static string DownsizeImage {
            get {
                return ResourceManager.GetString("DownsizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce image size to current window&apos;s. This reduces memory usage for images larger than the screen&apos;s..
        /// </summary>
        public static string DownsizeImageInfo {
            get {
                return ResourceManager.GetString("DownsizeImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsize image.
        /// </summary>
        public static string DownsizeImageShortcut {
            get {
                return ResourceManager.GetString("DownsizeImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsize On.
        /// </summary>
        public static string DownsizeOnTooltip {
            get {
                return ResourceManager.GetString("DownsizeOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail List.
        /// </summary>
        public static string EnableThumbnailList {
            get {
                return ResourceManager.GetString("EnableThumbnailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a list of thumbnails of all images on the side..
        /// </summary>
        public static string EnableThumbnailListInfo {
            get {
                return ResourceManager.GetString("EnableThumbnailListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore image location.
        /// </summary>
        public static string ExploreImageLocationShortcut {
            get {
                return ResourceManager.GetString("ExploreImageLocationShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which file types are loaded into the viewer..
        /// </summary>
        public static string FileTypeInfo {
            get {
                return ResourceManager.GetString("FileTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon FIVIcon {
            get {
                object obj = ResourceManager.GetObject("FIVIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVerAvailableInfo {
            get {
                return ResourceManager.GetString("NewVerAvailableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image.
        /// </summary>
        public static string NextImageShortcut {
            get {
                return ResourceManager.GetString("NextImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string NoInternetInfo {
            get {
                return ResourceManager.GetString("NoInternetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause animation.
        /// </summary>
        public static string PauseAnimationShortcut {
            get {
                return ResourceManager.GetString("PauseAnimationShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image.
        /// </summary>
        public static string PreviousImageShortcut {
            get {
                return ResourceManager.GetString("PreviousImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shortcut.
        /// </summary>
        public static string RemoveShortcut {
            get {
                return ResourceManager.GetString("RemoveShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed.
        /// </summary>
        public static string RenamedWatcher {
            get {
                return ResourceManager.GetString("RenamedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetSettingsButton {
            get {
                return ResourceManager.GetString("ResetSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the displayed language..
        /// </summary>
        public static string ShownLanguageInfo {
            get {
                return ResourceManager.GetString("ShownLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Thumbnail List.
        /// </summary>
        public static string ShowThumbnailList {
            get {
                return ResourceManager.GetString("ShowThumbnailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Image.
        /// </summary>
        public static string StretchImage {
            get {
                return ResourceManager.GetString("StretchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always stretch images to fit the window..
        /// </summary>
        public static string StretchImageInfo {
            get {
                return ResourceManager.GetString("StretchImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch image.
        /// </summary>
        public static string StretchImageShortcut {
            get {
                return ResourceManager.GetString("StretchImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch On.
        /// </summary>
        public static string StretchOnTooltip {
            get {
                return ResourceManager.GetString("StretchOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Accent.
        /// </summary>
        public static string ThemeAccent {
            get {
                return ResourceManager.GetString("ThemeAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the accent colors..
        /// </summary>
        public static string ThemeAccentInfo {
            get {
                return ResourceManager.GetString("ThemeAccentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail List On.
        /// </summary>
        public static string ThumbnailListOnTooltip {
            get {
                return ResourceManager.GetString("ThumbnailListOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Resolution.
        /// </summary>
        public static string ThumbnailRes {
            get {
                return ResourceManager.GetString("ThumbnailRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolution (in pixels) of each thumbnail image. A lower number will reduce memory consumption and increase loading speed of each thumbnail. Default is 80. (40-240).
        /// </summary>
        public static string ThumbnailResInfo {
            get {
                return ResourceManager.GetString("ThumbnailResInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Size.
        /// </summary>
        public static string ThumbnailSize {
            get {
                return ResourceManager.GetString("ThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the size of each item of the thumbnail list. Default is 80. (40-240).
        /// </summary>
        public static string ThumbnailSizeInfo {
            get {
                return ResourceManager.GetString("ThumbnailSizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string UpdatingInfo {
            get {
                return ResourceManager.GetString("UpdatingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Sensitivity.
        /// </summary>
        public static string ZoomSensitivity {
            get {
                return ResourceManager.GetString("ZoomSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the zoom in and out sensitivity of the image. (Default is 1.00).
        /// </summary>
        public static string ZoomSensitivityInfo {
            get {
                return ResourceManager.GetString("ZoomSensitivityInfo", resourceCulture);
            }
        }
    }
}
