//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIVStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FIVStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Changes.
        /// </summary>
        public static string AllWatcher {
            get {
                return ResourceManager.GetString("AllWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string ChangedWatcher {
            get {
                return ResourceManager.GetString("ChangedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedWatcher {
            get {
                return ResourceManager.GetString("CreatedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Light and Dark theme..
        /// </summary>
        public static string DarkModeInfo {
            get {
                return ResourceManager.GetString("DarkModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DeletedWatcher {
            get {
                return ResourceManager.GetString("DeletedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image .
        /// </summary>
        public static string DeleteImageShortcut {
            get {
                return ResourceManager.GetString("DeleteImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsize Image.
        /// </summary>
        public static string DownsizeImage {
            get {
                return ResourceManager.GetString("DownsizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce image size to current window&apos;s. This reduces memory usage for images larger than screen&apos;s..
        /// </summary>
        public static string DownsizeImageInfo {
            get {
                return ResourceManager.GetString("DownsizeImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsize image .
        /// </summary>
        public static string DownsizeImageShortcut {
            get {
                return ResourceManager.GetString("DownsizeImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore image location .
        /// </summary>
        public static string ExploreImageLocationShortcut {
            get {
                return ResourceManager.GetString("ExploreImageLocationShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon FIVIcon {
            get {
                object obj = ResourceManager.GetObject("FIVIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get image orientation.
        /// </summary>
        public static string ImgOrientationFailedMsg {
            get {
                return ResourceManager.GetString("ImgOrientationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image .
        /// </summary>
        public static string NextImageShortcut {
            get {
                return ResourceManager.GetString("NextImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string OpenFileLocation {
            get {
                return ResourceManager.GetString("OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause animation .
        /// </summary>
        public static string PauseAnimationShortcut {
            get {
                return ResourceManager.GetString("PauseAnimationShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image .
        /// </summary>
        public static string PreviousImageShortcut {
            get {
                return ResourceManager.GetString("PreviousImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed.
        /// </summary>
        public static string RenamedWatcher {
            get {
                return ResourceManager.GetString("RenamedWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the displayed language..
        /// </summary>
        public static string ShownLanguageInfo {
            get {
                return ResourceManager.GetString("ShownLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Image.
        /// </summary>
        public static string StretchImage {
            get {
                return ResourceManager.GetString("StretchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always stretch images to fit the window..
        /// </summary>
        public static string StretchImageInfo {
            get {
                return ResourceManager.GetString("StretchImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch image .
        /// </summary>
        public static string StretchImageShortcut {
            get {
                return ResourceManager.GetString("StretchImageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the accent colors..
        /// </summary>
        public static string ThemeAccentInfo {
            get {
                return ResourceManager.GetString("ThemeAccentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the zoom in and out sensitivity of the image. (Default is 1.00).
        /// </summary>
        public static string ZoomSensitivityInfo {
            get {
                return ResourceManager.GetString("ZoomSensitivityInfo", resourceCulture);
            }
        }
    }
}
